---
title: "Sampling dist vs. variance"
output: html_document
---

\

## Load packages and generate data
```{r setup, message=FALSE}
library(tidyverse)
library(MASS)
library(cowplot)

d1 <- tibble(values = c(mvrnorm(50, 2, 1, empirical = TRUE),
                        mvrnorm(50, 2.5, 1, empirical = TRUE)),
             group = rep(c("Ctrl", "Drug"), each = 50))

d2 <- tibble(values = c(mvrnorm(50, 2, 2^2, empirical = TRUE),
                        mvrnorm(50, 2.5, 2^2, empirical = TRUE)),
             group = rep(c("Ctrl", "Drug"), each = 50))

d3 <- tibble(values = c(mvrnorm(50, 2, 4^2, empirical = TRUE),
                        mvrnorm(50, 2.5, 4^2, empirical = TRUE)),
             group = rep(c("Ctrl", "Drug"), each = 50))
```

\

## Plotting data
```{r, fig.height=2, message=FALSE, out.width = "100%", warning=FALSE}
p1 <- d1 %>% 
  ggplot(aes(y = values,
             x = group,
             fill = group))+
  geom_bar(stat = "summary",
           fun = "mean",
           position = position_dodge(0.9),
           color = "black")+
  geom_errorbar(stat = "summary",
                fun.data = "mean_sdl",
                fun.args = list(mult = 1),
                width = 0.3,
                position = position_dodge(0.9))+
  theme_minimal()+
  scale_fill_manual(values = c("grey70", "cornflowerblue"))+
  coord_cartesian(ylim=c(-2,6.5))

p2 <- d2 %>% 
  ggplot(aes(y = values,
             x = group,
             fill = group))+
  geom_bar(stat = "summary",
           fun = "mean",
           position = position_dodge(0.9),
           color = "black")+
  geom_errorbar(stat = "summary",
                fun.data = "mean_sdl",
                fun.args = list(mult = 1),
                width = 0.3,
                position = position_dodge(0.9))+
  theme_minimal()+
  scale_fill_manual(values = c("grey70", "cornflowerblue"))+
  coord_cartesian(ylim=c(-2,6.5))

p3 <- d3 %>% 
  ggplot(aes(y = values,
             x = group,
             fill = group))+
  geom_bar(stat = "summary",
           fun = "mean",
           position = position_dodge(0.9),
           color = "black")+
  geom_errorbar(stat = "summary",
                fun.data = "mean_sdl",
                fun.args = list(mult = 1),
                width = 0.3,
                position = position_dodge(0.9))+
  theme_minimal()+
  scale_fill_manual(values = c("grey70", "cornflowerblue"))+
  coord_cartesian(ylim=c(-2,6.5))

plot_grid(p1, p2, p3, ncol = 3)
```

\

## Calculate mean differences
```{r, message=FALSE}
m1 <- d1 %>% 
  group_by(group) %>% 
  summarise(m = mean(values)) %>% 
  summarise(d = diff(m)) %>% 
  pull()

m2 <- d2 %>% 
  group_by(group) %>% 
  summarise(m = mean(values)) %>% 
  summarise(d = diff(m)) %>% 
  pull()

m3 <- d3 %>% 
  group_by(group) %>% 
  summarise(m = mean(values)) %>% 
  summarise(d = diff(m)) %>% 
  pull()

```

\

## Function for randomization
```{r}
rand_mean_diff <- function(data, col, group){
  data %>% 
    transmute({{group}},
              shuffled = sample({{col}}, replace = FALSE)) %>% 
    group_by({{group}}) %>% 
    summarise(m = mean(shuffled)) %>% 
    summarise(d = diff(m))
}
```

\

## Repeating function, seperately for each data set
```{r message=FALSE, warning=FALSE}
res1 <- map_dfr(1:1000, ~rand_mean_diff(d1, values, group))
res2 <- map_dfr(1:1000, ~rand_mean_diff(d2, values, group))
res3 <- map_dfr(1:1000, ~rand_mean_diff(d3, values, group))
```

\

## Plotting results
```{r, fig.height=2, message=FALSE, out.width = "100%"}
p1 <- res1 %>% 
  ggplot(aes(x = d))+
  geom_histogram()+
  geom_vline(xintercept = m1,
             color = "red",
             linetype = "dashed")+
  theme_minimal()+
  labs(title = "SD = 1")

p2 <- res2 %>% 
  ggplot(aes(x = d))+
  geom_histogram()+
  geom_vline(xintercept = m2,
             color = "red",
             linetype = "dashed")+
  theme_minimal()+
  labs(title = "SD = 2")

p3 <- res3 %>% 
  ggplot(aes(x = d))+
  geom_histogram()+
  geom_vline(xintercept = m3,
             color = "red",
             linetype = "dashed")+
  theme_minimal()+
  labs(title = "SD = 4")

plot_grid(p1, p2, p3, ncol = 3)
```

